//
// Generated file, do not edit! Created by opp_msgc 4.2 from packet.msg.
//

#ifndef _PACKET_M_H_
#define _PACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>packet.msg</tt> by opp_msgc.
 * <pre>
 * packet Packet {
 * 	double x;
 * 	double segmentLength;
 * 	double nEstimate;
 * 	int toSenderGateIndex;	
 *     int routingList[];
 *     int manager;
 * }
 * </pre>
 */
class Packet : public ::cPacket
{
  protected:
    double x_var;
    double segmentLength_var;
    double nEstimate_var;
    int toSenderGateIndex_var;
    int *routingList_var; // array ptr
    unsigned int routingList_arraysize;
    int manager_var;

  private:
    void copy(const Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Packet&);

  public:
    Packet(const char *name=NULL, int kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const {return new Packet(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getSegmentLength() const;
    virtual void setSegmentLength(double segmentLength);
    virtual double getNEstimate() const;
    virtual void setNEstimate(double nEstimate);
    virtual int getToSenderGateIndex() const;
    virtual void setToSenderGateIndex(int toSenderGateIndex);
    virtual void setRoutingListArraySize(unsigned int size);
    virtual unsigned int getRoutingListArraySize() const;
    virtual int getRoutingList(unsigned int k) const;
    virtual void setRoutingList(unsigned int k, int routingList);
    virtual int getManager() const;
    virtual void setManager(int manager);
};

inline void doPacking(cCommBuffer *b, Packet& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


#endif // _PACKET_M_H_
